PYTHON_FLASK_JSONRPC_VERSION = master
PYTHON_FLASK_JSONRPC_SOURCE = flask-jsonrpc-master.tar.gz
PYTHON_FLASK_JSONRPC_SITE = http://www.go-unified.com/firebrick
PYTHON_FLASK_JSONRPC_LICENSE = BSD-3c
PYTHON_FLASK_JSONRPC_LICENSE_FILES = LICENSE
PYTHON_FLASK_JSONRPC_SETUP_TYPE = setuptools

$(eval $(python-package))