PYTHON_JSONPICKLE_VERSION = 0.9.2
PYTHON_JSONPICKLE_SOURCE = jsonpickle-0.9.2.tar.gz
PYTHON_JSONPICKLE_SITE = http://www.go-unified.com/firebrick
PYTHON_JSONPICKLE_LICENSE = BSD-3c
PYTHON_JSONPICKLE_LICENSE_FILES = LICENSE
PYTHON_JSONPICKLE_SETUP_TYPE = setuptools

$(eval $(python-package))